export interface Surah {
  number: number;
  name: string;
  ayat: number;
}

// Data lengkap 114 Surat Al-Quran
export const QURAN_SURAHS: Surah[] = [
  { number: 1,   name: "Al-Fatihah",    ayat: 7   },
  { number: 2,   name: "Al-Baqarah",    ayat: 286 },
  { number: 3,   name: "Ali 'Imran",    ayat: 200 },
  { number: 4,   name: "An-Nisa'",      ayat: 176 },
  { number: 5,   name: "Al-Ma'idah",    ayat: 120 },
  { number: 6,   name: "Al-An'am",      ayat: 165 },
  { number: 7,   name: "Al-A'raf",      ayat: 206 },
  { number: 8,   name: "Al-Anfal",      ayat: 75  },
  { number: 9,   name: "At-Taubah",     ayat: 129 },
  { number: 10,  name: "Yunus",         ayat: 109 },
  { number: 11,  name: "Hud",           ayat: 123 },
  { number: 12,  name: "Yusuf",         ayat: 111 },
  { number: 13,  name: "Ar-Ra'd",       ayat: 43  },
  { number: 14,  name: "Ibrahim",       ayat: 52  },
  { number: 15,  name: "Al-Hijr",       ayat: 99  },
  { number: 16,  name: "An-Nahl",       ayat: 128 },
  { number: 17,  name: "Al-Isra'",      ayat: 111 },
  { number: 18,  name: "Al-Kahf",       ayat: 110 },
  { number: 19,  name: "Maryam",        ayat: 98  },
  { number: 20,  name: "Ta Ha",         ayat: 135 },
  { number: 21,  name: "Al-Anbiya'",    ayat: 112 },
  { number: 22,  name: "Al-Hajj",       ayat: 78  },
  { number: 23,  name: "Al-Mu'minun",   ayat: 118 },
  { number: 24,  name: "An-Nur",        ayat: 64  },
  { number: 25,  name: "Al-Furqan",     ayat: 77  },
  { number: 26,  name: "Asy-Syu'ara'",  ayat: 227 },
  { number: 27,  name: "An-Naml",       ayat: 93  },
  { number: 28,  name: "Al-Qashash",    ayat: 88  },
  { number: 29,  name: "Al-'Ankabut",   ayat: 69  },
  { number: 30,  name: "Ar-Rum",        ayat: 60  },
  { number: 31,  name: "Luqman",        ayat: 34  },
  { number: 32,  name: "As-Sajdah",     ayat: 30  },
  { number: 33,  name: "Al-Ahzab",      ayat: 73  },
  { number: 34,  name: "Saba'",         ayat: 54  },
  { number: 35,  name: "Fatir",         ayat: 45  },
  { number: 36,  name: "Ya Sin",        ayat: 83  },
  { number: 37,  name: "As-Saffat",     ayat: 182 },
  { number: 38,  name: "Shad",          ayat: 88  },
  { number: 39,  name: "Az-Zumar",      ayat: 75  },
  { number: 40,  name: "Ghafir",        ayat: 85  },
  { number: 41,  name: "Fusshilat",     ayat: 54  },
  { number: 42,  name: "Asy-Syura",     ayat: 53  },
  { number: 43,  name: "Az-Zukhruf",    ayat: 89  },
  { number: 44,  name: "Ad-Dukhan",     ayat: 59  },
  { number: 45,  name: "Al-Jasiyah",    ayat: 37  },
  { number: 46,  name: "Al-Ahqaf",      ayat: 35  },
  { number: 47,  name: "Muhammad",      ayat: 38  },
  { number: 48,  name: "Al-Fath",       ayat: 29  },
  { number: 49,  name: "Al-Hujurat",    ayat: 18  },
  { number: 50,  name: "Qaf",           ayat: 45  },
  { number: 51,  name: "Az-Zariyat",    ayat: 60  },
  { number: 52,  name: "At-Tur",        ayat: 49  },
  { number: 53,  name: "An-Najm",       ayat: 62  },
  { number: 54,  name: "Al-Qamar",      ayat: 55  },
  { number: 55,  name: "Ar-Rahman",     ayat: 78  },
  { number: 56,  name: "Al-Waqi'ah",    ayat: 96  },
  { number: 57,  name: "Al-Hadid",      ayat: 29  },
  { number: 58,  name: "Al-Mujadilah",  ayat: 22  },
  { number: 59,  name: "Al-Hasyr",      ayat: 24  },
  { number: 60,  name: "Al-Mumtahanah", ayat: 13  },
  { number: 61,  name: "As-Saff",       ayat: 14  },
  { number: 62,  name: "Al-Jumu'ah",    ayat: 11  },
  { number: 63,  name: "Al-Munafiqun",  ayat: 11  },
  { number: 64,  name: "At-Tagabun",    ayat: 18  },
  { number: 65,  name: "At-Talaq",      ayat: 12  },
  { number: 66,  name: "At-Tahrim",     ayat: 12  },
  { number: 67,  name: "Al-Mulk",       ayat: 30  },
  { number: 68,  name: "Al-Qalam",      ayat: 52  },
  { number: 69,  name: "Al-Haqqah",     ayat: 52  },
  { number: 70,  name: "Al-Ma'arij",    ayat: 44  },
  { number: 71,  name: "Nuh",           ayat: 28  },
  { number: 72,  name: "Al-Jinn",       ayat: 28  },
  { number: 73,  name: "Al-Muzzammil",  ayat: 20  },
  { number: 74,  name: "Al-Muddassir",  ayat: 56  },
  { number: 75,  name: "Al-Qiyamah",    ayat: 40  },
  { number: 76,  name: "Al-Insan",      ayat: 31  },
  { number: 77,  name: "Al-Mursalat",   ayat: 50  },
  { number: 78,  name: "An-Naba'",      ayat: 40  },
  { number: 79,  name: "An-Nazi'at",    ayat: 46  },
  { number: 80,  name: "'Abasa",        ayat: 42  },
  { number: 81,  name: "At-Takwir",     ayat: 29  },
  { number: 82,  name: "Al-Infitar",    ayat: 19  },
  { number: 83,  name: "Al-Mutaffifin", ayat: 36  },
  { number: 84,  name: "Al-Insyiqaq",   ayat: 25  },
  { number: 85,  name: "Al-Buruj",      ayat: 22  },
  { number: 86,  name: "At-Tariq",      ayat: 17  },
  { number: 87,  name: "Al-A'la",       ayat: 19  },
  { number: 88,  name: "Al-Gasyiyah",   ayat: 26  },
  { number: 89,  name: "Al-Fajr",       ayat: 30  },
  { number: 90,  name: "Al-Balad",      ayat: 20  },
  { number: 91,  name: "Asy-Syams",     ayat: 15  },
  { number: 92,  name: "Al-Lail",       ayat: 21  },
  { number: 93,  name: "Ad-Duha",       ayat: 11  },
  { number: 94,  name: "Asy-Syarh",     ayat: 8   },
  { number: 95,  name: "At-Tin",        ayat: 8   },
  { number: 96,  name: "Al-'Alaq",      ayat: 19  },
  { number: 97,  name: "Al-Qadr",       ayat: 5   },
  { number: 98,  name: "Al-Bayyinah",   ayat: 8   },
  { number: 99,  name: "Az-Zalzalah",   ayat: 8   },
  { number: 100, name: "Al-'Adiyat",    ayat: 11  },
  { number: 101, name: "Al-Qari'ah",    ayat: 11  },
  { number: 102, name: "At-Takasur",    ayat: 8   },
  { number: 103, name: "Al-'Asr",       ayat: 3   },
  { number: 104, name: "Al-Humazah",    ayat: 9   },
  { number: 105, name: "Al-Fil",        ayat: 5   },
  { number: 106, name: "Quraisy",       ayat: 4   },
  { number: 107, name: "Al-Ma'un",      ayat: 7   },
  { number: 108, name: "Al-Kausar",     ayat: 3   },
  { number: 109, name: "Al-Kafirun",    ayat: 6   },
  { number: 110, name: "An-Nasr",       ayat: 3   },
  { number: 111, name: "Al-Lahab",      ayat: 5   },
  { number: 112, name: "Al-Ikhlas",     ayat: 4   },
  { number: 113, name: "Al-Falaq",      ayat: 5   },
  { number: 114, name: "An-Nas",        ayat: 6   },
];

export const getSurahByNumber = (num: number): Surah | undefined =>
  QURAN_SURAHS.find(s => s.number === num);

export const calcHafalanPercent = (ayatReached: number, totalAyat: number): number =>
  totalAyat > 0 ? Math.round((ayatReached / totalAyat) * 100) : 0;

export const validateAyatInput = (input: number, totalAyat: number): boolean =>
  input >= 0 && input <= totalAyat;
